# Generated by Django 4.2.9 on 2024-01-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='age',
        ),
        migrations.AddField(
            model_name='music',
            name='song',
            field=models.FileField(default=7, upload_to='media'),
            preserve_default=False,
        ),
    ]
